# Generated by Django 5.2.16 on 2026-08-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.CharField(max_length=500),
        ),
    ]
