# Generated by Django 5.2.16 on 2026-08-13 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='banner',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='profession',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profil',
            name='speciality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profil',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('technical', 'Technique'), ('soft', 'Soft Skills'), ('language', 'Langue'), ('communication', 'Communication'), ('management', 'Management'), ('other', 'Autre')], default='other', max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profil.profil')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
