# Generated by Django 5.2.16 on 2026-07-17 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='event_covers/')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('format', models.CharField(choices=[('online', 'En ligne'), ('presentiel', 'Présentiel')], max_length=20)),
                ('categorie', models.CharField(choices=[('business', 'Business'), ('design', 'Design'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('education', 'Education'), ('autre', 'Autre')], max_length=20)),
                ('capacite', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('status', models.CharField(choices=[('publier', 'Publier'), ('brouillon', 'Brouillon'), ('live', 'Live')], default='brouillon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
